name: doclok_mobile

description: DocLok — secure document vault (Android/iOS client)

publish_to: 'none'

version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.0
  flutter_secure_storage: ^9.2.2
  file_picker: 10.3.10
  path_provider: ^2.1.4
  open_filex: ^4.5.0
  flutter_file_saver: ^0.10.0

  google_fonts: ^6.2.1
  provider: ^6.1.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true